# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d3382c5c27b578867e914439937c78c382b1bd1ecff0f5740fb65901fe8e048ef81b399d0868c95cad021e89d9b298775223c9a9a40f7ab3c98fc78e57e5fa

test:
  secret_key_base: 54bd9ac7447292559d9cbf25024feaa2e4f75d5f9866d4856efb51539305aade9a1f26d9fe2d36a54311981792aa8bbf5ad1ce739d30f7e6cadef3e4deb3ce2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
