# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3422884959c61b581870b6828f12961188ff98cc5573dd25f3d0978bdaa0a4c1aa5e5276753d24da6e59d6e6dc77796b2aec0a42b486b3db192953df2cae277c

test:
  secret_key_base: dc5ebdbea14bf9d1a7216975de40e36855b9274d8e73f5ddf38918bbd18a0ea2c9015769b64bd258fdbeea272d17d6d9e942c730455880c086c0e205ad5d92af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
